application: iemtreasurehunt
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: index.php
- url: /index\.php
  script: index.php
- url: /play\.php
  script: play.php
- url: /login\.php
  script: login.php  
- url: /logout\.php
  script: logout.php
- url: /register\.php
  script: register.php
- url: /forum\.php
  script: forum.php
- url: /leader\.php
  script: leader.php
  
  
- url: /class/operator\.php
  script: class/operator.php
- url: /class/forum_manager\.php
  script: class/forum_manager.php  


- url: /class
  static_dir: class  
- url: /css
  static_dir: css
- url: /images
  static_dir: images  
- url: /docs
  static_dir: docs
- url: /files
  static_dir: files
- url: /js
  static_dir: js
- url: /less
  static_dir: less
- url: /private
  static_dir: private  
- url: /fonts
  static_dir: fonts  
- url: /(.*\.(gif|png|jpg|js|png|ttf|svg|wof|pdf|doc|docx|html))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|js|png|ttf|svg|wof|pdf|doc|docx|html))
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico  