<?php
define('T_USER_ID',$_SESSION['treasure_user_id']);
define('T_NAME',$_SESSION['treasure_name']);
define('T_ROLE',$_SESSION['treasure_user_role']);
define('T_USERNAME',$_SESSION['treasure_username']);
define('T_LOGGED',$_SESSION['treasure_logged']);
define('T_MAXLEVEL',25);
define('T_FORUM_PAGE',6);
?>